import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {chromium} = require('../../empfängererklärung_form/.tools/browser/node_modules/playwright');
const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
let checks = 0;
function check(condition,label) { assert.ok(condition,label); checks++; console.log('PASS: '+label); }
try {
  const context = await browser.newContext({viewport:{width:1280,height:1000}});
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8097/?pagename=reklamation');
  await page.locator('.rf-form').waitFor({state:'visible'});
  check(await page.locator('[data-item]').count() === 1,'one article row initially');
  await page.locator('.rf-submit[type=submit]').click();
  check(await page.locator('[data-error-for=first_name]').innerText() !== '','required fields are shown');
  await page.locator('[name=first_name]').fill('Erika');
  await page.locator('[name=last_name]').fill('Musterfrau');
  await page.locator('[name=email]').fill('erika@example.test');
  await page.locator('[name=order_number]').fill('AUF-BROWSER-1');
  await page.locator('[name=customer_number]').fill('C-123');
  await page.locator('.rf-submit[type=submit]').click();
  check((await page.locator('[data-error-for=order_number]').innerText()).includes('PS, A-PV, AST oder RE'),'invalid order prefix blocked in browser');
  check((await page.locator('[data-error-for=customer_number]').innerText()).includes('KN oder K'),'invalid customer prefix blocked in browser');
  await page.locator('[name=order_number]').fill('RE-BROWSER-1');
  await page.locator('[name=customer_number]').fill('KN-123');
  await page.locator('[data-article]').fill('Defekter Testartikel');
  await page.locator('[data-quantity]').selectOption('2');
  await page.locator('[data-add-item]').click();
  check(await page.locator('[data-item]').count() === 2,'second article can be added');
  await page.locator('[data-item]').nth(1).locator('[data-article]').fill('Zweiter Artikel');
  await page.locator('[data-item]').nth(1).locator('[data-quantity]').selectOption('3');
  await page.locator('[data-item]').nth(1).locator('[data-remove-item]').click();
  check(await page.locator('[data-item]').count() === 1,'article can be removed');
  await page.locator('[name=refund_agreement][value=no]').check();
  await page.locator('[name=privacy_confirmed]').check();
  await page.waitForTimeout(2100);
  let submitted;
  page.on('request', request => { if (request.method()==='POST' && request.url().includes('/complaints')) submitted=request.postDataJSON(); });
  const responsePromise = page.waitForResponse(response => response.url().includes('/complaints'));
  await page.locator('.rf-submit[type=submit]').click();
  const response = await responsePromise;
  if (!response.ok()) console.log('SUBMIT RESPONSE',response.status(),await response.text());
  await page.locator('.rf-success').waitFor({state:'visible',timeout:30000});
  check(submitted.items.length === 1 && submitted.items[0].quantity === 2,'structured item payload submitted');
  check(submitted.refund_agreement === 'no','refund choice submitted');
  const url = await page.locator('.rf-download').getAttribute('href');
  const pdf = await context.request.get(url);
  check(pdf.status() === 200 && (await pdf.body()).subarray(0,5).toString() === '%PDF-','token downloads generated PDF');
  const withoutToken = new URL(url); withoutToken.searchParams.delete('token');
  check((await context.request.get(withoutToken.toString())).status() === 403,'download without token denied');
  check(errors.length === 0,'no browser runtime errors');
  await context.close();
  console.log(`${checks} Browser-Assertions bestanden.`);
} finally { await browser.close(); }
